import { Router, IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import projectsRouter from "./projects";
import postsRouter from "./posts";
import interactionsRouter from "./interactions";
import searchRouter from "./search";
import statsRouter from "./stats";
const router = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(projectsRouter);
router.use(postsRouter);
router.use(interactionsRouter);
router.use(searchRouter);
router.use(statsRouter);
export default router;