#!/bin/bash
# Vercel Environment Setup Script
# Run this script to set environment variables in Vercel

echo "🔐 Setting up Vercel environment variables..."
echo ""
echo "Environment Variables:"
echo "  DATABASE_URL: (You need to provide your PostgreSQL connection string)"
echo "  SESSION_SECRET: b12cc8a20d1fe17331d4df9467477cd15107fe9b2d7e4b5db9a352b6baa255f7"
echo "  NODE_ENV: production"
echo ""
echo "📝 To set these manually in Vercel:"
echo "1. Go to: https://vercel.com/dashboard/project-settings"
echo "2. Click on 'Environment Variables'"
echo "3. Add each variable below:"
echo ""
echo "   Key: DATABASE_URL"
echo "   Value: (your PostgreSQL connection string)"
echo "   Environments: Production, Preview, Development"
echo ""
echo "   Key: SESSION_SECRET"
echo "   Value: b12cc8a20d1fe17331d4df9467477cd15107fe9b2d7e4b5db9a352b6baa255f7"
echo "   Environments: Production, Preview, Development"
echo ""
echo "   Key: NODE_ENV"
echo "   Value: production"
echo "   Environments: Production"
echo ""
echo "🚀 Then redeploy your project:"
echo "   https://vercel.com/dashboard/project-settings/deployments"
echo ""
